name: my_travels
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  lottie: ^2.6.0
  get_storage: ^2.1.1
  equatable: ^2.0.5
  dotted_border: ^2.1.0
  flutter_easyloading: ^3.0.5
  step_progress_indicator: ^1.0.2
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  date_picker_timeline: ^1.2.5
  calendar_date_picker2: ^0.5.3
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.14.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  google_sign_in: ^6.1.6
  local_auth: ^2.1.7
  brasil_fields: ^1.14.0
  cached_network_image: ^3.3.0
  firebase_storage: ^11.0.5
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lua-de-mel.png"
  adaptive_icon_background: "assets/images/lua-de-mel.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/lua-de-mel.png
  color_dark: "#ffffff"
  android_12:
  fullscreen: true

  